version: 1.2.{build}
image: Visual Studio 2017
branches:
  only:
  - master
init:
# Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/ClosedXML.TableReader/ClosedXML.TableReader.csproj --verbosity m
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: r+6q617sAaF2tWqiq0GExKIPfsG6riYVWrDiL6QTLtSy5YJRSign3r4FCLUbJhW8
notifications:
- provider: Email
  to:
  - phone.rene@gmail.com
  subject: Table Reader Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
