name: Build .NET Core

on:
  push:
  # branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ClosedXML.TableReader.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ClosedXML.TableReader.sln --no-restore --verbosity normal
    
       
